name = "vectimus-api"
main = "src/index.ts"
compatibility_date = "2026-03-14"

[[routes]]
pattern = "api.vectimus.com"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "vectimus-incidents"
database_id = "a908783d-5ff8-48fb-970b-a0b8c4168a7c"

[site]
bucket = "./dashboard"
